"""
Extension System — Hot-loadable plugins
=========================================

Extensions live in the ``extensions/`` folder as individual Python files.
Each file must define a class that inherits from :class:`Extension`.

Features
--------
*   **Hot reload** – edit a file on disk, the manager detects the change
    and reloads it without restarting the bot.
*   **Sensitive-action confirmation** – actions like kick / leave / ban
    are intercepted and require an explicit ``/confirm`` from an admin.
*   **Lifecycle hooks** – ``on_load``, ``on_unload``, ``on_reload``.
*   **Per-extension config** – each extension can declare its own config
    dict, stored in ``extensions/<name>.json``.

Quick start
-----------

Create ``extensions/hello.py``::

    from onebot_server.extension import Extension
    from onebot_server.events import GroupMessageEvent
    from onebot_server.actions import SendGroupMsgAction
    from onebot_server.segments import build_message, AtSegment

    class HelloExt(Extension):
        name = "hello"
        version = "1.0.0"
        description = "Replies 'hello' in groups"

        async def on_group_message(self, event, client):
            if "hello" in event.get_text().lower():
                await client.send(SendGroupMsgAction(
                    group_id=event.group_id,
                    message=build_message(
                        AtSegment.someone(event.user_id), " Hello!",
                    ),
                ))
"""

from __future__ import annotations

import asyncio
import importlib
import json
import sys
import time
import traceback
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Type, Union

from loguru import logger

from onebot_server.actions import BaseAction
from onebot_server.events import BaseEvent

# ---------------------------------------------------------------------------
# Sensitive action registry
# ---------------------------------------------------------------------------

# Action names that require admin confirmation before execution
SENSITIVE_ACTIONS: Set[str] = {
    "set_group_kick",
    "set_group_ban",
    "set_group_whole_ban",
    "set_group_leave",
    "set_group_admin",
    "set_restart",
    "delete_msg",
}


# ---------------------------------------------------------------------------
# Confirmation request
# ---------------------------------------------------------------------------


@dataclass
class ConfirmRequest:
    """
    A pending confirmation for a sensitive action.

    Generated by :class:`ExtensionManager` when a sensitive action is
    intercepted. The action is **not** executed until
    :meth:`ExtensionManager.confirm` is called with the matching token.
    """

    token: str
    action_name: str
    params: Dict[str, Any]
    reason: str
    requested_by: int  # user_id who triggered it
    group_id: Optional[int]  # group context (if any)
    created_at: float = field(default_factory=time.time)
    action_obj: Optional[BaseAction] = None

    # TTL in seconds – confirmations expire
    TTL: int = 300

    @property
    def is_expired(self) -> bool:
        return (time.time() - self.created_at) > self.TTL

    def to_dict(self) -> Dict[str, Any]:
        return {
            "token": self.token[:8] + "...",
            "action": self.action_name,
            "params": self.params,
            "reason": self.reason,
            "requested_by": self.requested_by,
            "group_id": self.group_id,
            "expires_in": int(self.TTL - (time.time() - self.created_at)),
        }


# ---------------------------------------------------------------------------
# Base Extension class (users inherit from this)
# ---------------------------------------------------------------------------


class Extension:
    """
    Base class for all extensions.

    Subclass and override the event hooks you care about. The class-level
    attributes ``name``, ``version`` and ``description`` are used by the
    manager for logging and the CLI.

    Class attributes
    ----------------
    name : str
        Unique extension identifier (defaults to class name).
    version : str
        SemVer string.
    description : str
        Short human-readable description.
    priority : int
        Lower = runs first. Default 100.
    admin_only : bool
        If True, only admin user_ids can trigger this extension's commands.
    sensitive : bool
        If True, all actions sent via this extension go through confirmation.

    Lifecycle hooks
    ---------------
    on_load(manager)    – called after the extension is imported
    on_unload()         – called before the extension is removed
    on_reload()         – called after a hot-reload

    Event hooks (same names as :class:`onebot_server.server.OneBotHandler`)
    ---------------------------------------------------------------------
    on_event(event, client)
    on_message(event, client)
    on_group_message(event, client)
    on_private_message(event, client)
    on_notice(event, client)
    on_request(event, client)
    on_meta(event, client)
    """

    #: Override in subclass
    name: str = ""
    version: str = "0.1.0"
    description: str = ""
    priority: int = 100
    admin_only: bool = False
    sensitive: bool = False

    # Set by the manager
    _manager: Optional["ExtensionManager"] = None
    _config_path: Optional[Path] = None
    _config: Dict[str, Any] = field(default_factory=dict) if False else {}  # type: ignore

    # ------------------------------------------------------------------
    # Config helpers
    # ------------------------------------------------------------------

    def get_config(self, key: str, default: Any = None) -> Any:
        """Read a config value (loaded from ``extensions/<name>.json``)."""
        return self._config.get(key, default)

    def set_config(self, key: str, value: Any) -> None:
        """Write a config value and persist to disk."""
        self._config[key] = value
        self._save_config()

    def _save_config(self) -> None:
        if not self._config_path:
            return
        try:
            self._config_path.write_text(
                json.dumps(self._config, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )
        except OSError as e:
            logger.warning(f"[{self.name}] Failed to save config: {e}")

    def _load_config(self) -> None:
        if not self._config_path or not self._config_path.exists():
            self._config = {}
            return
        try:
            self._config = json.loads(self._config_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as e:
            logger.warning(f"[{self.name}] Config parse error: {e}; using empty config")
            self._config = {}

    # ------------------------------------------------------------------
    # Lifecycle (designed to be overridden)
    # ------------------------------------------------------------------

    async def on_load(self, manager: "ExtensionManager") -> None:
        """Called after the extension is successfully imported."""
        self._manager = manager
        self._load_config()
        logger.info(f"[{self.name}] loaded v{self.version}")

    async def on_unload(self) -> None:
        """Called before the extension is removed or the bot shuts down."""
        logger.info(f"[{self.name}] unloaded")

    async def on_reload(self) -> None:
        """Called after a hot-reload (file changed on disk)."""
        self._load_config()
        logger.info(f"[{self.name}] reloaded")

    # ------------------------------------------------------------------
    # Event hooks (default: do nothing)
    # ------------------------------------------------------------------

    async def on_event(self, event: BaseEvent, client) -> None: ...
    async def on_message(self, event, client) -> None: ...
    async def on_group_message(self, event, client) -> None: ...
    async def on_private_message(self, event, client) -> None: ...
    async def on_notice(self, event, client) -> None: ...
    async def on_request(self, event, client) -> None: ...
    async def on_meta(self, event, client) -> None: ...


# ---------------------------------------------------------------------------
# Extension Manager
# ---------------------------------------------------------------------------


class ExtensionManager:
    """
    Discovers, loads, reloads and unloads extensions at runtime.

    Parameters
    ----------
    extensions_dir : str | Path
        Folder containing extension ``.py`` files.
    admin_ids : set[int]
        QQ user_ids that are allowed to confirm sensitive actions and
        run admin-only extensions.
    watch : bool
        If True, a background task watches the extensions folder for
        file changes and hot-reloads automatically.
    """

    def __init__(
        self,
        extensions_dir: Union[str, Path] = "extensions",
        admin_ids: Optional[Set[int]] = None,
        watch: bool = True,
    ) -> None:
        self.extensions_dir = Path(extensions_dir)
        self.extensions_dir.mkdir(parents=True, exist_ok=True)
        self.admin_ids: Set[int] = admin_ids or set()
        self.watch = watch

        #: name -> Extension instance
        self._extensions: Dict[str, Extension] = {}
        #: name -> module object
        self._modules: Dict[str, Any] = {}
        #: name -> file mtime (for change detection)
        self._mtimes: Dict[str, float] = {}

        # Pending confirmation requests
        self._confirmations: Dict[str, ConfirmRequest] = {}

        # Background watcher task
        self._watcher_task: Optional[asyncio.Task] = None

        # Client reference (set by server)
        self._client = None

        logger.info(f"Extension dir: {self.extensions_dir.resolve()}")

    # ------------------------------------------------------------------
    # Client binding
    # ------------------------------------------------------------------

    def bind_client(self, client) -> None:
        """Attach the WS client so extensions can send actions."""
        self._client = client

    # ------------------------------------------------------------------
    # Discovery & loading
    # ------------------------------------------------------------------

    def discover(self) -> List[str]:
        """Return the list of extension file names (without .py)."""
        files = sorted(self.extensions_dir.glob("*.py"))
        names = [f.stem for f in files if f.stem != "__init__"]
        logger.debug(f"Discovered extensions: {names}")
        return names

    async def load_all(self) -> None:
        """Load (or reload) every extension file in the folder."""
        for name in self.discover():
            try:
                await self.load(name)
            except Exception:
                logger.error(f"Failed to load extension '{name}':\n{traceback.format_exc()}")

    async def load(self, name: str) -> bool:
        """
        Load or reload a single extension by file stem.

        Returns True on success. Awaits ``on_load`` so config is
        ready immediately after this returns.
        """
        filepath = self.extensions_dir / f"{name}.py"
        if not filepath.exists():
            logger.error(f"Extension '{name}' not found at {filepath}")
            return False

        # Unload first if already loaded (hot-reload path)
        was_loaded = name in self._extensions
        if was_loaded:
            await self._extensions[name].on_unload()
            mod_name = f"_onebot_ext_{name}"
            if mod_name in sys.modules:
                del sys.modules[mod_name]

        # Import fresh
        mod_name = f"_onebot_ext_{name}"
        spec = importlib.util.spec_from_file_location(mod_name, filepath)
        if not spec or not spec.loader:
            logger.error(f"Cannot create spec for '{name}'")
            return False
        module = importlib.util.module_from_spec(spec)
        sys.modules[mod_name] = module
        try:
            spec.loader.exec_module(module)
        except Exception:
            logger.error(f"Extension '{name}' import error:\n{traceback.format_exc()}")
            del sys.modules[mod_name]
            return False

        # Find the Extension subclass
        ext_class: Optional[Type[Extension]] = None
        for attr_name in dir(module):
            attr = getattr(module, attr_name)
            if isinstance(attr, type) and issubclass(attr, Extension) and attr is not Extension:
                ext_class = attr
                break

        if not ext_class:
            logger.error(f"Extension '{name}': no Extension subclass found")
            del sys.modules[mod_name]
            return False

        # Instantiate
        try:
            ext = ext_class()
        except Exception:
            logger.error(f"Extension '{name}' init error:\n{traceback.format_exc()}")
            return False

        # Set metadata
        if not ext.name:
            ext.name = name
        ext._manager = self
        ext._config_path = self.extensions_dir / f"{name}.json"

        # Store
        self._extensions[ext.name] = ext
        self._modules[ext.name] = module
        self._mtimes[ext.name] = filepath.stat().st_mtime

        # Lifecycle — await so config is persisted before we return
        await ext.on_load(self)

        action = "reloaded" if was_loaded else "loaded"
        logger.success(f"Extension '{ext.name}' v{ext.version} {action} " f"({ext.description or 'no description'})")
        return True

    def unload(self, name: str) -> bool:
        """Unload an extension (calls ``on_unload``)."""
        ext = self._extensions.get(name)
        if not ext:
            logger.warning(f"Cannot unload '{name}': not loaded")
            return False

        async def _do_unload():
            await ext.on_unload()

        asyncio.create_task(_do_unload())
        del self._extensions[name]
        if name in self._modules:
            mod_name = self._modules[name].__name__
            del self._modules[name]
            if mod_name in sys.modules:
                del sys.modules[mod_name]
        self._mtimes.pop(name, None)
        logger.info(f"Extension '{name}' unloaded")
        return True

    # ------------------------------------------------------------------
    # Hot-reload watcher
    # ------------------------------------------------------------------

    async def start_watcher(self) -> None:
        """Start the background file-watcher task."""
        if not self.watch:
            return
        self._watcher_task = asyncio.create_task(self._watch_loop())
        logger.info("Extension hot-reload watcher started")

    async def stop_watcher(self) -> None:
        if self._watcher_task:
            self._watcher_task.cancel()
            self._watcher_task = None
            logger.info("Extension watcher stopped")

    async def _watch_loop(self) -> None:
        """Poll the extensions folder every 2 seconds for changes."""
        while True:
            try:
                await asyncio.sleep(2)
                for filepath in self.extensions_dir.glob("*.py"):
                    if filepath.stem == "__init__":
                        continue
                    name = filepath.stem
                    mtime = filepath.stat().st_mtime
                    old = self._mtimes.get(name)
                    if old is None or mtime > old:
                        logger.info(f"Change detected: {name}.py")
                        self.load(name)
            except asyncio.CancelledError:
                break
            except Exception:
                logger.error(f"Watcher error:\n{traceback.format_exc()}")

    # ------------------------------------------------------------------
    # Event dispatch
    # ------------------------------------------------------------------

    async def dispatch(self, event: BaseEvent, client) -> None:
        """
        Fan out an event to all loaded extensions in priority order.
        """
        # Sort by priority (lower first)
        exts = sorted(self._extensions.values(), key=lambda e: e.priority)

        for ext in exts:
            try:
                # Admin-only check
                if ext.admin_only:
                    uid = getattr(event, "user_id", 0)
                    if uid not in self.admin_ids:
                        continue

                # Dispatch to the most specific hook
                if hasattr(ext, "on_event"):
                    await ext.on_event(event, client)

                etype = getattr(event, "post_type_value", "")
                if etype == "message":
                    await ext.on_message(event, client)
                    if hasattr(event, "message_type"):
                        if event.message_type == "group":
                            await ext.on_group_message(event, client)
                        elif event.message_type == "private":
                            await ext.on_private_message(event, client)
                elif etype == "notice":
                    await ext.on_notice(event, client)
                elif etype == "request":
                    await ext.on_request(event, client)
                elif etype == "meta_event":
                    await ext.on_meta(event, client)

            except Exception:
                logger.error(
                    f"Extension '{ext.name}' error handling " f"{event.__class__.__name__}:\n{traceback.format_exc()}"
                )

    # ------------------------------------------------------------------
    # Sensitive action confirmation
    # ------------------------------------------------------------------

    def is_sensitive(self, action_name: str) -> bool:
        """Check whether an action name is in the sensitive list."""
        return action_name in SENSITIVE_ACTIONS

    def request_confirmation(
        self,
        action: BaseAction,
        reason: str,
        requested_by: int,
        group_id: Optional[int] = None,
    ) -> ConfirmRequest:
        """
        Create a pending confirmation for a sensitive action.

        Returns the :class:`ConfirmRequest` object – the action is NOT
        executed yet.
        """
        import uuid

        token = uuid.uuid4().hex[:16]
        req = ConfirmRequest(
            token=token,
            action_name=action.action,
            params=action._collect_params(),
            reason=reason,
            requested_by=requested_by,
            group_id=group_id,
            action_obj=action,
        )
        self._confirmations[token] = req
        logger.warning(
            f"Sensitive action '{action.action}' requested by {requested_by} " f"| token={token} | reason={reason}"
        )
        return req

    async def confirm(self, token: str, admin_id: int) -> Optional[BaseAction]:
        """
        Approve a pending confirmation and execute the action.

        Returns the action object if approved, or ``None`` if the token
        is invalid / expired / not authorised.
        """
        if admin_id not in self.admin_ids:
            logger.warning(f"Non-admin {admin_id} tried to confirm {token}")
            return None

        req = self._confirmations.pop(token, None)
        if not req:
            logger.warning(f"Confirm token not found: {token}")
            return None

        if req.is_expired:
            logger.warning(f"Confirm token expired: {token}")
            return None

        if not req.action_obj:
            logger.error(f"Confirm token {token} has no action_obj")
            return None

        logger.success(f"Admin {admin_id} approved '{req.action_name}' (token={token})")

        # Execute via client
        if self._client:
            await self._client.send(req.action_obj)
        return req.action_obj

    def cancel(self, token: str, admin_id: int) -> bool:
        """Reject / cancel a pending confirmation."""
        if admin_id not in self.admin_ids:
            return False
        req = self._confirmations.pop(token, None)
        if req:
            logger.info(f"Admin {admin_id} cancelled '{req.action_name}'")
            return True
        return False

    def list_confirmations(self) -> List[Dict[str, Any]]:
        """Return all pending confirmations (for CLI / admin commands)."""
        # Clean expired
        expired = [t for t, r in self._confirmations.items() if r.is_expired]
        for t in expired:
            del self._confirmations[t]
        return [r.to_dict() for r in self._confirmations.values()]

    # ------------------------------------------------------------------
    # Introspection
    # ------------------------------------------------------------------

    def list_extensions(self) -> List[Dict[str, Any]]:
        """Return metadata for all loaded extensions."""
        return [
            {
                "name": e.name,
                "version": e.version,
                "description": e.description,
                "priority": e.priority,
                "admin_only": e.admin_only,
                "sensitive": e.sensitive,
            }
            for e in sorted(self._extensions.values(), key=lambda x: x.priority)
        ]

    def get_extension(self, name: str) -> Optional[Extension]:
        return self._extensions.get(name)


# ---------------------------------------------------------------------------
# Module-level convenience
# ---------------------------------------------------------------------------

__all__ = [
    "Extension",
    "ExtensionManager",
    "ConfirmRequest",
    "SENSITIVE_ACTIONS",
]
